/*
 * Monsters
 */
export const LOADING_MONSTERS_INITIATED = 'LOADING_MONSTERS_INITIATED';
export const MONSTERS_ALREADY_LOADED = 'MONSTERS_ALREADY_LOADED';
export const LOADING_MONSTERS_SUCCESS = 'LOADING_MONSTERS_SUCCESS';
export const LOADING_MONSTERS_ERROR = 'LOADING_MONSTERS_ERROR';
export const LOADING_MONSTER_INITIATED = 'LOADING_MONSTER_INITIATED';
export const MONSTER_ALREADY_LOADED = 'MONSTER_ALREADY_LOADED';
export const LOADING_MONSTER_SUCCESS = 'LOADING_MONSTER_SUCCESS';
export const LOADING_MONSTER_ERROR = 'LOADING_MONSTER_ERROR';

/*
 * Items
 */
export const LOADING_ITEMS_INITIATED = 'LOADING_ITEMS_INITIATED';
export const ITEMS_ALREADY_LOADED = 'ITEMS_ALREADY_LOADED';
export const LOADING_ITEMS_SUCCESS = 'LOADING_ITEMS_SUCCESS';
export const LOADING_ITEMS_ERROR = 'LOADING_ITEMS_ERROR';
export const LOADING_ITEM_INITIATED = 'LOADING_ITEM_INITIATED';
export const ITEM_ALREADY_LOADED = 'ITEM_ALREADY_LOADED';
export const LOADING_ITEM_SUCCESS = 'LOADING_ITEM_SUCCESS';
export const LOADING_ITEM_ERROR = 'LOADING_ITEM_ERROR';


/*
 * History
 */
export const LOADING_LOGS_INITIATED = 'LOADING_LOGS_INITIATED';
export const LOGS_ALREADY_LOADED = 'LOGS_ALREADY_LOADED';
export const LOADING_LOGS_SUCCESS = 'LOADING_LOGS_SUCCESS';
export const LOADING_LOGS_ERROR = 'LOADING_LOGS_ERROR';

/*
 * Log
 */
export const LOADING_LOG_INITIATED = 'LOADING_LOG_INITIATED';
export const LOG_ALREADY_LOADED = 'LOG_ALREADY_LOADED';
export const LOADING_LOG_SUCCESS = 'LOADING_LOG_SUCCESS';
export const LOADING_LOG_ERROR = 'LOADING_LOG_ERROR';

export const UPDATING_LOG_INITIATED = 'UPDATING_LOG_INITIATED';
export const UPDATING_LOG_SUCCESS = 'UPDATING_LOG_SUCCESS';
export const UPDATING_LOG_ERROR = 'UPDATING_LOG_ERROR';

export const CREATING_LOG_INITIATED = 'CREATING_LOG';
export const CREATING_LOG_SUCCESS = 'CREATING_LOG_SUCCESS';
export const CREATING_LOG_ERROR = 'CREATING_LOG_ERROR';

export const DELETING_LOGS_INITIATED = 'DELETING_LOGS_INITIATED';
export const DELETING_LOGS_SUCCESS = 'DELETING_LOGS_SUCCESS';
export const DELETING_LOGS_ERROR = 'DELETING_LOGS_ERROR';

/*
 * Note
 */
export const CREATE_NOTE = 'CREATE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';

/*
 * Weather
 */
export const LOADING_WEATHER_INITIATED = 'LOADING_WEATHER_INITIATED';
export const WEATHER_ALREADY_LOADED = 'WEATHER_ALREADY_LOADED';
export const LOADING_WEATHER_SUCCESS = 'LOADING_WEATHER_SUCCESS';
export const LOADING_WEATHER_ERROR = 'LOADING_WEATHER_ERROR';

/*
 * Login
 */
export const LOG_IN_INITIATED = 'LOG_IN_INITIATED';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT_INITIATED = 'LOG_OUT_INITIATED';
export const LOG_OUT_ERROR = 'LOG_OUT_ERROR';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

/*
 * User
 */
export const CREATE_NEW_USER_INITIATED = 'CREATE_NEW_USER_INITIATED';
export const CREATE_NEW_USER_ERROR = 'CREATE_NEW_USER_ERROR';
export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS';
export const GET_USER_INITIATED = 'GET_USER_INITIATED';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

/*
 * Ping
 */
export const PING_ERROR = 'PING_ERROR';
export const PING_SUCCESS = 'PING_SUCCESS';
