/*
 * Monsters
 */
export const LOADING_MONSTERS_INITIATED = 'LOADING_MONSTERS_INITIATED';
export const LOADING_MONSTERS_SUCCESS = 'LOADING_MONSTERS_SUCCESS';
export const LOADING_MONSTERS_ERROR = 'LOADING_MONSTERS_ERROR';
export const LOADING_MONSTER_INITIATED = 'LOADING_MONSTER_INITIATED';
export const LOADING_MONSTER_SUCCESS = 'LOADING_MONSTER_SUCCESS';
export const LOADING_MONSTER_ERROR = 'LOADING_MONSTER_ERROR';

/*
 * Items
 */
export const LOADING_ITEMS_INITIATED = 'LOADING_ITEMS_INITIATED';
export const LOADING_ITEMS_SUCCESS = 'LOADING_ITEMS_SUCCESS';
export const LOADING_ITEMS_ERROR = 'LOADING_ITEMS_ERROR';
export const LOADING_ITEM_INITIATED = 'LOADING_ITEM_INITIATED';
export const LOADING_ITEM_SUCCESS = 'LOADING_ITEM_SUCCESS';
export const LOADING_ITEM_ERROR = 'LOADING_ITEM_ERROR';
export const SAVING_ITEM_INITIATED = 'SAVING_ITEM_INITIATED';
export const SAVING_ITEM_SUCCESS = 'SAVING_ITEM_SUCCESS';
export const SAVING_ITEM_ERROR = 'SAVING_ITEM_ERROR';
export const CREATING_ITEM_INITIATED = 'CREATING_ITEM_INITIATED';
export const CREATING_ITEM_SUCCESS = 'CREATING_ITEM_SUCCESS';
export const CREATING_ITEM_ERROR = 'CREATING_ITEM_ERROR';
export const DELETING_ITEM_INITIATED = 'DELETING_ITEM_INITIATED';
export const DELETING_ITEM_SUCCESS = 'DELETING_ITEM_SUCCESS';
export const DELETING_ITEM_ERROR = 'DELETING_ITEM_ERROR';
