/*
 * Monsters
 */
export const LOADING_MONSTERS_INITIATED = 'LOADING_MONSTERS_INITIATED';
export const MONSTERS_ALREADY_LOADED = 'MONSTERS_ALREADY_LOADED';
export const LOADING_MONSTERS_SUCCESS = 'LOADING_MONSTERS_SUCCESS';
export const LOADING_MONSTERS_ERROR = 'LOADING_MONSTERS_ERROR';
export const LOADING_MONSTER_INITIATED = 'LOADING_MONSTER_INITIATED';
export const MONSTER_ALREADY_LOADED = 'MONSTER_ALREADY_LOADED';
export const LOADING_MONSTER_SUCCESS = 'LOADING_MONSTER_SUCCESS';
export const LOADING_MONSTER_ERROR = 'LOADING_MONSTER_ERROR';

/*
 * Items
 */
export const LOADING_ITEMS_INITIATED = 'LOADING_ITEMS_INITIATED';
export const ITEMS_ALREADY_LOADED = 'ITEMS_ALREADY_LOADED';
export const LOADING_ITEMS_SUCCESS = 'LOADING_ITEMS_SUCCESS';
export const LOADING_ITEMS_ERROR = 'LOADING_ITEMS_ERROR';
export const LOADING_ITEM_INITIATED = 'LOADING_ITEM_INITIATED';
export const ITEM_ALREADY_LOADED = 'ITEM_ALREADY_LOADED';
export const LOADING_ITEM_SUCCESS = 'LOADING_ITEM_SUCCESS';
export const LOADING_ITEM_ERROR = 'LOADING_ITEM_ERROR';


/*
 * History
 */
export const LOADING_LOGS_INITIATED = 'LOADING_LOGS_INITIATED';
export const LOGS_ALREADY_LOADED = 'LOGS_ALREADY_LOADED';
export const LOADING_LOGS_SUCCESS = 'LOADING_LOGS_SUCCESS';
export const LOADING_LOGS_ERROR = 'LOADING_LOGS_ERROR';

/*
 * Log
 */
export const LOADING_LOG_INITIATED = 'LOADING_LOG_INITIATED';
export const LOG_ALREADY_LOADED = 'LOG_ALREADY_LOADED';
export const LOADING_LOG_SUCCESS = 'LOADING_LOG_SUCCESS';
export const LOADING_LOG_ERROR = 'LOADING_LOG_ERROR';

export const SAVING_LOG_INITIATED = 'SAVING_LOG';
export const SAVING_LOG_SUCCESS = 'SAVING_LOG_SUCCESS';
export const SAVING_LOG_ERROR = 'SAVING_LOG_ERROR';

/*
 * Note
 */
export const SAVING_NOTE = 'SAVING_NOTE_INITIATED';
export const SAVING_NOTE_SUCCESS = 'SAVING_NOTE_SUCCESS';
export const SAVING_NOTE_ERROR = 'SAVING_NOTE_ERROR';
